name: Daily Automation Script

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours (at 0:00, 3:00, 6:00, 9:00, 12:00, 15:00, 18:00, 21:00 UTC)
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Automate Script
        run: node automate.js
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
